Added authorizationType parameter to CheckoutRequest
PayMaya/PayMaya-Android-SDK-v2 pull request #13
Opened 2021-04-24 16:34 UTC by jecsan

2021-04-27 01:19 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/CheckoutRequest.kt
> +    val authorizationType: AuthorizationType? = null,
This is a breaking change.
Since this has a default value, you can move this as last argument

2021-04-27 01:19 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/AuthorizationType.kt
> +public enum class AuthorizationType(val value: String) {
`public` is not needed. Please remove

2021-04-27 01:19 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/AuthorizationType.kt
> +    Normal("NORMAL"),
We use UPPER_CASE for enum.
If you use UPPER_CASE, then no need for `value` and custom serializer.

2021-04-27 01:19 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/AuthorizationType.kt
> +}
Add newline (EOF) for all new files

2021-04-27 01:19 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/common/serialization/AuthorizationTypeSerializer.kt
> +object AuthorizationTypeSerializer {
Check my comment above, you may not need a custom serializer.

2021-05-03 10:38 UTC, reestolonio requested changes
@jecsan please check some minor comments

2021-05-03 10:38 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/CheckoutRequest.kt
> +public data class CheckoutRequest(
`public` is the default visibility modifier in Kotlin. Remove this.

2021-05-03 10:38 UTC, reestolonio commented on sdk-demo/src/main/java/com/paymaya/sdk/android/demo/ui/cart/CartPresenter.kt
> +
Unnecessary change, remove this.

2021-05-03 10:38 UTC, reestolonio commented on sdk/src/main/java/com/paymaya/sdk/android/checkout/models/CheckoutRequest.kt
> +    ) : PayMayaRequest
Fix code alignment

```suggestion
) : PayMayaRequest
```

2021-05-04 01:16 UTC, reestolonio commented
Good with this @jecsan , appreciate the PR.

2021-05-04 01:17 UTC, reestolonio approved these changes

2021-05-05 04:02 UTC, rjarce commented
Looks good, thanks @jecsan

2021-05-05 04:02 UTC, merged